

services:
  laravel_api:
    container_name: laravel_api
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/var/www/html:delegated
      - ./logs:/var/www/html/storage/logs
      - ./vendor:/var/www/html/vendor
      - ./vendor/autoload.php:/var/www/html/vendor/autoload.php
      - ./storage:/var/www/html/storage

    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: tola2003
      MYSQL_DATABASE: tstore_db
      MYSQL_USER: tola
      MYSQL_PASSWORD: tola2003
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: tola
      PMA_PASSWORD: tola2003
      PMA_ABSOLUTE_URI: http://localhost:8080
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
